name: forecast-eval-env
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal=3.0.2
  - python=3.7.9
  - pip=20.2.4
  - r-base=3.6.3
  - glib
  - mscorefonts
  - r-cairo
  - r-devtools
  - r-directlabels
  - r-gridextra
  - r-reticulate
  - r-blogdown
  - r-svglite
  - r-dplyr
  - r-ggplot2
  - r-jsonlite
  - r-httr
  - r-codetools
  - r-maptools
  - r-purrr
  - r-rlang
  - r-tidyr
  - r-vctrs
  - r-farver
  - r-vctrs
  - r-testthat
  - r-isoband
  - r-ggrepel
  - r-plotly
  - r-usmap
  - r-readr
  - pandoc
  - fiona
  - geopandas
  - pandas
  - numpy
  - pillow
  - pyproj
  - matplotlib
  - pip:
      - covidcast==0.1.2
